ARG GVISOR_BASE=us-central1-docker.pkg.dev/veris-ai-prod/veris-sandbox/veris-gvisor:latest
FROM ${GVISOR_BASE}

COPY src /agent/src

WORKDIR /agent
COPY pyproject.toml uv.lock README.md /agent/
RUN uv sync --frozen --no-dev

WORKDIR /app
